# language: haskell

dist: trusty

env:
 # Doesn't build with GHC versions earlier than 8.0
 - GHCVER=8.0.2

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.24 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.24 update

script:
 - Scripts/travis-build.sh
